export interface Country { code:string; name:string; continent:string; currency?:string; eu?:boolean }
export const CONTINENT_COLORS: Record<string,string> = {
  'Europäische Union':'#3b82f6','Europa':'#6366f1',
  'Nordamerika':'#f59e0b','Südamerika':'#10b981',
  'Asien':'#ec4899','Naher Osten':'#f97316',
  'Afrika':'#84cc16','Ozeanien':'#06b6d4',
}
export const COUNTRIES_FULL: Country[] = [
  // Europäische Union
  {code:'AT',name:'Österreich',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'BE',name:'Belgien',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'BG',name:'Bulgarien',continent:'Europäische Union',currency:'BGN',eu:true},
  {code:'CY',name:'Zypern',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'CZ',name:'Tschechien',continent:'Europäische Union',currency:'CZK',eu:true},
  {code:'DE',name:'Deutschland',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'DK',name:'Dänemark',continent:'Europäische Union',currency:'DKK',eu:true},
  {code:'EE',name:'Estland',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'ES',name:'Spanien',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'FI',name:'Finnland',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'FR',name:'Frankreich',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'EL',name:'Griechenland',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'HR',name:'Kroatien',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'HU',name:'Ungarn',continent:'Europäische Union',currency:'HUF',eu:true},
  {code:'IE',name:'Irland',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'IT',name:'Italien',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'LT',name:'Litauen',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'LU',name:'Luxemburg',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'LV',name:'Lettland',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'MT',name:'Malta',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'NL',name:'Niederlande',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'PL',name:'Polen',continent:'Europäische Union',currency:'PLN',eu:true},
  {code:'PT',name:'Portugal',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'RO',name:'Rumänien',continent:'Europäische Union',currency:'RON',eu:true},
  {code:'SE',name:'Schweden',continent:'Europäische Union',currency:'SEK',eu:true},
  {code:'SI',name:'Slowenien',continent:'Europäische Union',currency:'EUR',eu:true},
  {code:'SK',name:'Slowakei',continent:'Europäische Union',currency:'EUR',eu:true},
  // Europa (nicht EU)
  {code:'AD',name:'Andorra',continent:'Europa',currency:'EUR'},
  {code:'AL',name:'Albanien',continent:'Europa'},
  {code:'AM',name:'Armenien',continent:'Europa'},
  {code:'AZ',name:'Aserbaidschan',continent:'Europa'},
  {code:'BA',name:'Bosnien-Herzeg.',continent:'Europa'},
  {code:'BY',name:'Belarus',continent:'Europa'},
  {code:'CH',name:'Schweiz',continent:'Europa',currency:'CHF'},
  {code:'GE',name:'Georgien',continent:'Europa'},
  {code:'GB',name:'Großbritannien',continent:'Europa',currency:'GBP'},
  {code:'IS',name:'Island',continent:'Europa'},
  {code:'LI',name:'Liechtenstein',continent:'Europa',currency:'CHF'},
  {code:'MC',name:'Monaco',continent:'Europa',currency:'EUR'},
  {code:'MD',name:'Moldau',continent:'Europa'},
  {code:'ME',name:'Montenegro',continent:'Europa',currency:'EUR'},
  {code:'MK',name:'Nordmazedonien',continent:'Europa'},
  {code:'NO',name:'Norwegen',continent:'Europa',currency:'NOK'},
  {code:'RS',name:'Serbien',continent:'Europa'},
  {code:'RU',name:'Russland',continent:'Europa'},
  {code:'SM',name:'San Marino',continent:'Europa',currency:'EUR'},
  {code:'TR',name:'Türkei',continent:'Europa'},
  {code:'UA',name:'Ukraine',continent:'Europa'},
  {code:'VA',name:'Vatikanstadt',continent:'Europa',currency:'EUR'},
  {code:'XK',name:'Kosovo',continent:'Europa',currency:'EUR'},
  // Nordamerika
  {code:'BZ',name:'Belize',continent:'Nordamerika'},
  {code:'CA',name:'Kanada',continent:'Nordamerika',currency:'CAD'},
  {code:'CR',name:'Costa Rica',continent:'Nordamerika'},
  {code:'CU',name:'Kuba',continent:'Nordamerika'},
  {code:'DO',name:'Dom. Republik',continent:'Nordamerika'},
  {code:'GT',name:'Guatemala',continent:'Nordamerika'},
  {code:'HN',name:'Honduras',continent:'Nordamerika'},
  {code:'JM',name:'Jamaika',continent:'Nordamerika'},
  {code:'MX',name:'Mexiko',continent:'Nordamerika'},
  {code:'NI',name:'Nicaragua',continent:'Nordamerika'},
  {code:'PA',name:'Panama',continent:'Nordamerika'},
  {code:'SV',name:'El Salvador',continent:'Nordamerika'},
  {code:'TT',name:'Trinidad & Tobago',continent:'Nordamerika'},
  {code:'US',name:'USA',continent:'Nordamerika',currency:'USD'},
  // Südamerika
  {code:'AR',name:'Argentinien',continent:'Südamerika'},
  {code:'BO',name:'Bolivien',continent:'Südamerika'},
  {code:'BR',name:'Brasilien',continent:'Südamerika',currency:'BRL'},
  {code:'CL',name:'Chile',continent:'Südamerika'},
  {code:'CO',name:'Kolumbien',continent:'Südamerika'},
  {code:'EC',name:'Ecuador',continent:'Südamerika'},
  {code:'GY',name:'Guyana',continent:'Südamerika'},
  {code:'PE',name:'Peru',continent:'Südamerika'},
  {code:'PY',name:'Paraguay',continent:'Südamerika'},
  {code:'SR',name:'Suriname',continent:'Südamerika'},
  {code:'UY',name:'Uruguay',continent:'Südamerika'},
  {code:'VE',name:'Venezuela',continent:'Südamerika'},
  // Asien
  {code:'BD',name:'Bangladesch',continent:'Asien'},
  {code:'CN',name:'China',continent:'Asien',currency:'CNY'},
  {code:'HK',name:'Hongkong',continent:'Asien'},
  {code:'ID',name:'Indonesien',continent:'Asien'},
  {code:'IN',name:'Indien',continent:'Asien'},
  {code:'JP',name:'Japan',continent:'Asien',currency:'JPY'},
  {code:'KH',name:'Kambodscha',continent:'Asien'},
  {code:'KR',name:'Südkorea',continent:'Asien'},
  {code:'KZ',name:'Kasachstan',continent:'Asien'},
  {code:'KG',name:'Kirgisistan',continent:'Asien'},
  {code:'LA',name:'Laos',continent:'Asien'},
  {code:'LK',name:'Sri Lanka',continent:'Asien'},
  {code:'MM',name:'Myanmar',continent:'Asien'},
  {code:'MN',name:'Mongolei',continent:'Asien'},
  {code:'MY',name:'Malaysia',continent:'Asien'},
  {code:'NP',name:'Nepal',continent:'Asien'},
  {code:'PH',name:'Philippinen',continent:'Asien'},
  {code:'PK',name:'Pakistan',continent:'Asien'},
  {code:'SG',name:'Singapur',continent:'Asien'},
  {code:'TJ',name:'Tadschikistan',continent:'Asien'},
  {code:'TM',name:'Turkmenistan',continent:'Asien'},
  {code:'TW',name:'Taiwan',continent:'Asien'},
  {code:'TH',name:'Thailand',continent:'Asien'},
  {code:'UZ',name:'Usbekistan',continent:'Asien'},
  {code:'VN',name:'Vietnam',continent:'Asien'},
  // Naher Osten
  {code:'AE',name:'Ver. Arab. Emirate',continent:'Naher Osten'},
  {code:'AF',name:'Afghanistan',continent:'Naher Osten'},
  {code:'BH',name:'Bahrain',continent:'Naher Osten'},
  {code:'IL',name:'Israel',continent:'Naher Osten'},
  {code:'IQ',name:'Irak',continent:'Naher Osten'},
  {code:'IR',name:'Iran',continent:'Naher Osten'},
  {code:'JO',name:'Jordanien',continent:'Naher Osten'},
  {code:'KW',name:'Kuwait',continent:'Naher Osten'},
  {code:'LB',name:'Libanon',continent:'Naher Osten'},
  {code:'OM',name:'Oman',continent:'Naher Osten'},
  {code:'QA',name:'Katar',continent:'Naher Osten'},
  {code:'SA',name:'Saudi-Arabien',continent:'Naher Osten'},
  {code:'SY',name:'Syrien',continent:'Naher Osten'},
  {code:'YE',name:'Jemen',continent:'Naher Osten'},
  // Afrika
  {code:'AO',name:'Angola',continent:'Afrika'},
  {code:'CI',name:"Côte d'Ivoire",continent:'Afrika'},
  {code:'CM',name:'Kamerun',continent:'Afrika'},
  {code:'DZ',name:'Algerien',continent:'Afrika'},
  {code:'EG',name:'Ägypten',continent:'Afrika'},
  {code:'ET',name:'Äthiopien',continent:'Afrika'},
  {code:'GH',name:'Ghana',continent:'Afrika'},
  {code:'KE',name:'Kenia',continent:'Afrika'},
  {code:'LY',name:'Libyen',continent:'Afrika'},
  {code:'MA',name:'Marokko',continent:'Afrika'},
  {code:'MG',name:'Madagaskar',continent:'Afrika'},
  {code:'MZ',name:'Mosambik',continent:'Afrika'},
  {code:'NG',name:'Nigeria',continent:'Afrika'},
  {code:'SN',name:'Senegal',continent:'Afrika'},
  {code:'TN',name:'Tunesien',continent:'Afrika'},
  {code:'TZ',name:'Tansania',continent:'Afrika'},
  {code:'UG',name:'Uganda',continent:'Afrika'},
  {code:'ZA',name:'Südafrika',continent:'Afrika'},
  {code:'ZM',name:'Sambia',continent:'Afrika'},
  {code:'ZW',name:'Simbabwe',continent:'Afrika'},
  // Ozeanien
  {code:'AU',name:'Australien',continent:'Ozeanien',currency:'AUD'},
  {code:'FJ',name:'Fidschi',continent:'Ozeanien'},
  {code:'NZ',name:'Neuseeland',continent:'Ozeanien'},
  {code:'PG',name:'Papua-Neuguinea',continent:'Ozeanien'},
]

export const COUNTRIES_SORTED=[...COUNTRIES_FULL].sort((a,b)=>a.name.localeCompare(b.name,'de'))

export function getCountriesByContinent():Record<string,Country[]>{
  const r:Record<string,Country[]>={}
  const order=['Europäische Union','Europa','Nordamerika','Südamerika','Asien','Naher Osten','Afrika','Ozeanien']
  const sorted=[...COUNTRIES_FULL].sort((a,b)=>a.name.localeCompare(b.name,'de'))
  for(const c of sorted){ if(!r[c.continent])r[c.continent]=[]; r[c.continent].push(c) }
  // Sortiere Gruppen nach Kontinent-Reihenfolge
  return Object.fromEntries(order.filter(k=>r[k]).map(k=>[k,r[k]]))
}

export function getCountry(code:string):Country|undefined{ return COUNTRIES_FULL.find(c=>c.code===code) }
export function getCountryBadgeColor(code:string):string{ const c=getCountry(code); return CONTINENT_COLORS[c?.continent??'']??'#64748b' }
export const COUNTRIES:Record<string,string>=Object.fromEntries(COUNTRIES_FULL.map(c=>[c.code,c.name]))

export interface CurrencyInfo { code:string; name:string; symbol:string; country:string; isoFlag:string }
export const CURRENCIES_FULL:CurrencyInfo[]=[
  {code:'EUR',name:'Euro',                  symbol:'€',  country:'Europäische Union',  isoFlag:'EU'},
  {code:'USD',name:'US-Dollar',             symbol:'$',  country:'USA',                isoFlag:'US'},
  {code:'GBP',name:'Britisches Pfund',      symbol:'£',  country:'Großbritannien',     isoFlag:'GB'},
  {code:'CHF',name:'Schweizer Franken',     symbol:'Fr.',country:'Schweiz',            isoFlag:'CH'},
  {code:'PLN',name:'Polnischer Złoty',      symbol:'zł', country:'Polen',              isoFlag:'PL'},
  {code:'SEK',name:'Schwedische Krone',     symbol:'kr', country:'Schweden',           isoFlag:'SE'},
  {code:'NOK',name:'Norwegische Krone',     symbol:'kr', country:'Norwegen',           isoFlag:'NO'},
  {code:'DKK',name:'Dänische Krone',        symbol:'kr', country:'Dänemark',           isoFlag:'DK'},
  {code:'CZK',name:'Tschechische Krone',    symbol:'Kč', country:'Tschechien',         isoFlag:'CZ'},
  {code:'HUF',name:'Ungarischer Forint',    symbol:'Ft', country:'Ungarn',             isoFlag:'HU'},
  {code:'RON',name:'Rumänischer Leu',       symbol:'lei',country:'Rumänien',           isoFlag:'RO'},
  {code:'BGN',name:'Bulgarischer Lew',      symbol:'лв', country:'Bulgarien',          isoFlag:'BG'},
  {code:'JPY',name:'Japanischer Yen',       symbol:'¥',  country:'Japan',              isoFlag:'JP'},
  {code:'CNY',name:'Chinesischer Yuan',     symbol:'¥',  country:'China',              isoFlag:'CN'},
  {code:'CAD',name:'Kanadischer Dollar',    symbol:'C$', country:'Kanada',             isoFlag:'CA'},
  {code:'AUD',name:'Australischer Dollar',  symbol:'A$', country:'Australien',         isoFlag:'AU'},
  {code:'HKD',name:'Hongkong-Dollar',       symbol:'HK$',country:'Hongkong',           isoFlag:'HK'},
  {code:'SGD',name:'Singapur-Dollar',       symbol:'S$', country:'Singapur',           isoFlag:'SG'},
  {code:'INR',name:'Indische Rupie',        symbol:'₹',  country:'Indien',             isoFlag:'IN'},
  {code:'KRW',name:'Südkoreanischer Won',   symbol:'₩',  country:'Südkorea',           isoFlag:'KR'},
  {code:'TRY',name:'Türkische Lira',        symbol:'₺',  country:'Türkei',             isoFlag:'TR'},
  {code:'ZAR',name:'Südafrikanischer Rand', symbol:'R',  country:'Südafrika',          isoFlag:'ZA'},
  {code:'BRL',name:'Brasilianischer Real',  symbol:'R$', country:'Brasilien',          isoFlag:'BR'},
  {code:'MXN',name:'Mexikanischer Peso',    symbol:'$',  country:'Mexiko',             isoFlag:'MX'},
  {code:'AED',name:'Dirham (VAE)',          symbol:'د.إ',country:'Ver. Arab. Emirate', isoFlag:'AE'},
  {code:'SAR',name:'Saudi Riyal',           symbol:'﷼',  country:'Saudi-Arabien',      isoFlag:'SA'},
  {code:'TWD',name:'Taiwan-Dollar',         symbol:'NT$',country:'Taiwan',             isoFlag:'TW'},
  {code:'THB',name:'Thai. Baht',            symbol:'฿',  country:'Thailand',           isoFlag:'TH'},
  {code:'MYR',name:'Malays. Ringgit',       symbol:'RM', country:'Malaysia',           isoFlag:'MY'},
  {code:'VND',name:'Vietnamesischer Dong',  symbol:'₫',  country:'Vietnam',            isoFlag:'VN'},
  {code:'IDR',name:'Indonesische Rupiah',   symbol:'Rp', country:'Indonesien',         isoFlag:'ID'},
  {code:'ILS',name:'Israelischer Schekel',  symbol:'₪',  country:'Israel',             isoFlag:'IL'},
  {code:'ISK',name:'Isländische Krone',     symbol:'kr', country:'Island',             isoFlag:'IS'},
  {code:'NZD',name:'Neuseeland-Dollar',     symbol:'NZ$',country:'Neuseeland',         isoFlag:'NZ'},
  {code:'RUB',name:'Russischer Rubel',      symbol:'₽',  country:'Russland',           isoFlag:'RU'},
  {code:'UAH',name:'Ukrainische Hrywnja',   symbol:'₴',  country:'Ukraine',            isoFlag:'UA'},
  {code:'PKR',name:'Pakistanische Rupie',   symbol:'₨',  country:'Pakistan',           isoFlag:'PK'},
  {code:'KZT',name:'Kasachst. Tenge',       symbol:'₸',  country:'Kasachstan',         isoFlag:'KZ'},
]
export function getCurrencyInfo(code:string):CurrencyInfo|undefined{ return CURRENCIES_FULL.find(c=>c.code===code) }
export const CURRENCIES=CURRENCIES_FULL.map(c=>c.code)
export const UNITS=['kg','g','mg','l','ml','piece','pcs','m','cm','mm','m2']
export function countryLabel(c:Country):string{ return `${c.code} – ${c.name}` }
